### ISSUE TITLE
not fitted for windows?

### ISSUE THREAD

**Issue by cmougin** [cyrbil/python_keepass_http#3]
Hi,
After pip install, simple "python -m keepasshttp www.amazon.com" fails, see traces below.
I noticed that no ~/.keepasshttp_key was created, as working on Windows. 
Workaround "kph = KeePassHTTP(storage="./keepasshttp_key", url="http://localhost:19455/")" didn't fix anything.
any help?
Christophe
full trace:
(base) c:\Utilisateurs\FR20340\OneDrive\Personnel\hacking\keepass-over-http>python -m keepasshttp www.amazon.com
Traceback (most recent call last):
  File "C:\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\lib\site-packages\keepasshttp\__main__.py", line 139, in <module>
    print(cmd_line())
  File "C:\Anaconda3\lib\site-packages\keepasshttp\__main__.py", line 133, in cmd_line
    credentials[credential] = kph.get(credential)
  File "C:\Anaconda3\lib\site-packages\keepasshttp\keepass_http.py", line 130, in get
    entries = self.search(key)
  File "C:\Anaconda3\lib\site-packages\keepasshttp\keepass_http.py", line 113, in search
    data = self._request("get-logins", Url=key, SortSelection=sort_keys)
  File "C:\Anaconda3\lib\site-packages\keepasshttp\keepass_http.py", line 189, in _request
    self._load()
  File "C:\Anaconda3\lib\site-packages\keepasshttp\keepass_http.py", line 152, in _load
    self.uid, self.db_hash = self._register()
  File "C:\Anaconda3\lib\site-packages\keepasshttp\keepass_http.py", line 171, in _register
    data = self._request("associate", Key=base64.b64encode(self.key))
  File "C:\Anaconda3\lib\site-packages\keepasshttp\keepass_http.py", line 203, in _request
    raise KeePassHTTPException("KeePassHTTP returned an error")  # pragma: no cover
keepasshttp.keepass_http.KeePassHTTPException: KeePassHTTP returned an error

(base) c:\Utilisateurs\FR20340\OneDrive\Personnel\hacking\keepass-over-http>

**Comment by cmougin** [comment]
Apologies, the issue is related to my proxy. 
On line 203, requests module fails to connect to local:19455 because of the environment variable declaring a proxy. by unsetting the env variables (del os.environ['HTTP_PROXY']) I managed to fix the issue, which is definitely not at your side.
so I'm happy with your module, finally. thank you for it !
